FROM ghcr.io/linuxserver/baseimage-kasmvnc:ubuntujammy

RUN \
  curl -fsSL -o google-chrome.deb "https://www.slimjet.com/chrome/download-chrome.php?file=files%2F104.0.5112.102%2Fgoogle-chrome-stable_current_amd64.deb" && \
  apt-get update && \
  apt-get install -y --no-install-recommends ./google-chrome.deb && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf google-chrome.deb

COPY /chrome /
